services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_database
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    tmpfs:
      - /var/lib/mysql  # Use tmpfs for MySQL data directory
   
  postgres_db:
    image: postgres:latest
    container_name: postgresql_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: mydatabase
    tmpfs:
      - /var/lib/postgresql/data  # Use tmpfs for PostgreSQL data directory