services:
  db:
    image: mysql:latest
    container_name: mysql_migration_from_database_container # Name for the container
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql # Initialize the database with initdb.sql

  postgres:
    image: postgres:latest
    container_name: postgresql_migration_to_database_container # Name for the container
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}