services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_migration_from_database_container
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    #volumes:
    #  - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql # Initialize the database with initdb.sql

  postgres_db:
    image: postgres:latest
    container_name: postgresql_migration_to_database_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: mydatabase